// <auto-generated />
namespace Sistema_Academico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addEstudiantes_Entitie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEstudiantes_Entitie));
        
        string IMigrationMetadata.Id
        {
            get { return "201707022239118_addEstudiantes_Entitie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
